$Color_Black = rgb(282828)
$Color_Red = rgb(cc241d)
$Color_Green = rgb(98971a)
$Color_Yellow = rgb(d79921)
$Color_Blue = rgb(458588)
$Color_Magenta = rgb(b16286)
$Color_Cyan = rgb(689d6a)
$Color_White = rgb(a89984)
$Bright_Black = rgb(928374)
$Bright_Red = rgb(fb4934)
$Bright_Green = rgb(b8bb26)
$Bright_Yellow = rgb(fabd2f)
$Bright_Blue = rgb(83a598)
$Bright_Magenta = rgb(d3869b)
$Bright_Cyan = rgb(8ec07c)
$Bright_White = rgb(ebdbb2)

