###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = foot
$browser = firefox
$ssh = ~/.config/fuzzel/fuzzel-ssh.sh
$fileManager = thunar
$menu = fuzzel
$lock = swaylock
$screenshot = slurp | grim -g - - | wl-copy

$brightness_up = brightnessctl -e4 -n2 set 5%+
$brightness_down = brightnessctl -e4 -n2 set 5%-

$volume_up = pactl set-sink-volume @DEFAULT_SINK@ +5%
$volume_down = pactl set-sink-volume @DEFAULT_SINK@ -5%
$volume_mute = pactl set-sink-mute @DEFAULT_SINK@ toggle
$mic_mute = pactl set-source-mute @DEFAULT_SOURCE@ toggle
